import type { GetServerSideProps, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import imageLoader from "../imageLoader";
import styles from "../styles/Home.module.css";
import { Character, Films, GetCharacterResults } from "../types/types";
import { FilmList } from "../data/movies";
import ItemListContainer from "../components/ItemListContainer/ItemListContainer";

const Home: NextPage<{ films: Films }> = ({ films }) => {
  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ItemListContainer
        items={films}
      />
    </div>
  );
};

  

  export const getServerSideProps : GetServerSideProps = async ( context ) => {
    const promise = new Promise (function (resolve, reject) {
      resolve(FilmList);
    })

    const res = await promise;

    return {
      props: {
        films: res,
      },
    };
  }

export default Home;
